export const pupsData = [
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "angry.jpeg",
    alt: "A dog looking moody",
  },
  {
    emotionTags: ["moody", "insomniac"],
    isGif: false,
    image: "angry2.jpeg",
    alt: "A dog looking moody",
  },
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "angry3.jpeg",
    alt: "A dog looking moody",
  },
  {
    emotionTags: ["confused", "sad"],
    isGif: false,
    image: "confused.jpeg",
    alt: "A dog looking confused",
  },
  {
    emotionTags: ["dominant", "moody"],
    isGif: false,
    image: "dominant.jpeg",
    alt: "A dog looking dominant",
  },
  {
    emotionTags: ["happy", "relaxed"],
    isGif: false,
    image: "happy.jpeg",
    alt: "A dog looking happy",
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "hungry.jpeg",
    alt: "A dog looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "hungry1.jpeg",
    alt: "A dog looking hungry",
  },
  {
    emotionTags: ["insomniac"],
    isGif: false,
    image: "insomnia.jpeg",
    alt: "A dog looking insomniac",
  },
  {
    emotionTags: ["insomniac"],
    isGif: false,
    image: "insomnia1.jpeg",
    alt: "A dog looking insomniac",
  },
  {
    emotionTags: ["relaxed"],
    isGif: false,
    image: "lazy.jpeg",
    alt: "A dog looking lazy",
  },
  {
    emotionTags: ["scared"],
    isGif: false,
    image: "nervous.jpeg",
    alt: "A dog looking nervous",
  },
  {
    emotionTags: ["sad"],
    isGif: false,
    image: "sad.jpeg",
    alt: "A dog looking sad",
  },
  {
    emotionTags: ["sad", "moody"],
    isGif: false,
    image: "sad1.jpeg",
    alt: "A dog looking sad",
  },
  {
    emotionTags: ["moody"],
    isGif: true,
    image: "angry.gif",
    alt: "A dog looking moody",
  },
  {
    emotionTags: ["moody"],
    isGif: true,
    image: "angry2.gif",
    alt: "A dog looking angry",
  },
  {
    emotionTags: ["confused"],
    isGif: true,
    image: "confused2.gif",
    alt: "A dog looking confused",
  },
  {
    emotionTags: ["dominant"],
    isGif: true,
    image: "dominant.gif",
    alt: "A dog looking dominant",
  },
  {
    emotionTags: ["happy"],
    isGif: true,
    image: "happy.gif",
    alt: "A dog looking happy",
  },
  {
    emotionTags: ["hungry", "sad", "confused"],
    isGif: true,
    image: "confused.gif",
    alt: "A dog looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "hungry.gif",
    alt: "A dog looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "hungry2.gif",
    alt: "A dog looking hungry",
  },
  {
    emotionTags: ["insomniac", "scared"],
    isGif: true,
    image: "insomnia2.gif",
    alt: "A dog looking insomniac",
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "lazy.gif",
    alt: "A dog looking relaxed",
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "relaxed2.gif",
    alt: "A dog looking relaxed",
  },
  {
    emotionTags: ["scared", "sad"],
    isGif: true,
    image: "nervous.gif",
    alt: "A dog looking nervous",
  },
  {
    emotionTags: ["scared"],
    isGif: true,
    image: "nervous2.gif",
    alt: "A dog looking scared",
  },
  {
    emotionTags: ["sad"],
    isGif: true,
    image: "sad.gif",
    alt: "A dog looking sad",
  },
];
